#!/bin/bash

# Write udev rules file for PGR devices.
cat <<EOF >/etc/udev/rules.d/71-pgr.rules
ATTRS{idVendor}=="1e10", MODE="0666", GROUP="pgrimaging"
KERNEL=="raw1394", MODE="0666", GROUP="pgrimaging"
KERNEL=="video1394*", MODE="0666", GROUP="pgrimaging"
KERNEL=="fw*", SUBSYSTEM=="firewire", ATTR{vendor}=="0x00b09d", MODE="0666", GROUP="pgrimaging"
EOF

# Refresh rules, trigger re-scan of connected devices.
udevadm control --reload-rules
udevadm trigger
